<a href="https://colab.research.google.com/github/jeniferganamuthu-max/Data-Analytics-Using-Python-Project/blob/main/Internship_from_Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks=np.array([99,98,87,90])
print(marks[1])

98


In [ ]:
import numpy as np
marks=np.array([97,87,90,92,95,77,65,72,12])
print(marks[1:4])

[87 90 92]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
new_arr=arr.reshape(5,2)
print(new_arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [ ]:
import numpy as np
marks=np.array([78,92,58,67,49])
average=np.mean(marks)
print(average)

68.8


In [ ]:
import numpy as np
marks=np.array([25,48,67,93,59])
average=np.median(marks)
print(average)

59.0


In [ ]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
print(a+b)
#[11 22 33 44]
print(a*b)
#[10 40 90 160]
print(np.sqrt(a))
#[1. 1.40 1.73.2.]
print(np.sum(a))
#10

[11 22 33 44]
[ 10  40  90 160]
[1.         1.41421356 1.73205081 2.        ]
10


**Practice**

In [ ]:
Sales=[10000,12000,25000,62000,98000]

total=sum(Sales)
avg=total/len(Sales)
high_Sales=max(Sales)
low_Sales=min(Sales)

print("Total:",total)
print("Average:",avg)
print("high_Sales:",high_Sales)
print("low_sales:",low_Sales)

Total: 207000
Average: 41400.0
high_Sales: 98000
low_sales: 10000


In [ ]:
scores=[85,98,62,56,73]

total=sum(scores)
average=total/len(scores)
highest=max(scores)
lowest=min(scores)

print("Total Score:",total)
print("Average Score:",average)
print("Highest Score:",highest)
print("Lowest Score:",lowest)

Total Score: 374
Average Score: 74.8
Highest Score: 98
Lowest Score: 56
