<a href="https://colab.research.google.com/github/jeniferganamuthu-max/Data-Analytics-Using-Python-Project/blob/main/Internship_from_Day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
  num=int(input("Enter the number:"))
  print(num)
except:
  print("Invalid input")

Enter the number:100
100


In [ ]:
def attendance(attended,total):
  return (attended / total) * 100
attended = int(input("classes Attended:"))
total = int(input("Total classes:"))

percent = attendance(attended,total)

print("Attendance Percentage =",round(percent,2),"%")
if percent >= 75:
  print("Eligible")
else:
  print("Not Eligible")

classes Attended:65


In [ ]:
def calculate_average(x,y,z):
    return(x+y+z)/3
try:
  x=int(input("Enter first number:"))
  y=int(input("Enter second number:"))
  z=int(input("Enter third number:"))
  print("calculate_average=",calculate_average(x,y,z))
except ValueError:
  print("Invalid Input")

Enter first number:10
Enter second number:20
Enter third number:30
calculate_average= 20.0


In [ ]:
import numpy as np
marks = np.array([80,98,87,90])
print(marks)

[80 98 87 90]


In [ ]:
import numpy as np
marks = np.array([
    [90,85,78],
    [92,88,95]
])
print(marks)

[[90 85 78]
 [92 88 95]]
